apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: hellosaanvika-dev

images:
  - name: docker.io/mrrobotthecoder/hellosaanvika
    newTag: 1.0.1

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: hellosaanvika-ingress

  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: hellosaanvika