apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hellosaanvika-ingress
spec:
  rules:
    - host: hellosaanvika.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hellosaanvika-svc
                port:
                  number: 80
  tls:
    - hosts:
        - hellosaanvika.com
      secretName: hellosaanvika-prod-tls
