apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: hellosaanvika-prod

images:
  - name: docker.io/mrrobotthecoder/hellosaanvika
    newTag: 2.0.0

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: hellosaanvika-ingress

  - path: resources-patch.yaml
    target:
      kind: Deployment
      name: hellosaanvika

  - path: probes-patch.yaml
    target:
      kind: Deployment
      name: hellosaanvika

  - path: rollout-patch.yaml
    target:
      kind: Deployment
      name: hellosaanvika